# Generated by Django 5.2.3 on 2025-06-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('goal_at_creation', models.CharField(help_text="The user's goal when this plan was created.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_prompt_text', models.TextField(blank=True, help_text='The exact prompt sent to the AI.')),
                ('ai_response_raw', models.JSONField(blank=True, help_text='The raw JSON response from the AI.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('notes', models.TextField(blank=True, help_text="General advice for the day, e.g., 'Drink 3L of water.'")),
                ('target_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('target_protein_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('target_carbs_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('target_fats_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_days', to='rest.fitnessplan')),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('description', models.CharField(help_text="e.g., 'Waakye with boiled egg and fish'", max_length=255)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.FloatField()),
                ('carbs_grams', models.FloatField()),
                ('fats_grams', models.FloatField()),
                ('portion_size', models.CharField(blank=True, help_text="e.g., '1 medium ladle', '2 pieces of chicken'", max_length=100)),
                ('nutrition_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='rest.nutritionday')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.FloatField(blank=True, help_text='Weight in kilograms (kg)', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in centimeters (cm)', null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very Active (hard exercise/sports 6-7 days a week)')], max_length=50, null=True)),
                ('goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('muscle_gain', 'Muscle Gain')], max_length=50, null=True)),
                ('dietary_preferences', models.TextField(blank=True, help_text="e.g., 'no red meat', 'prefers fish', 'allergic to groundnuts'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to='rest.profile'),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('title', models.CharField(help_text="e.g., 'Upper Body Strength' or 'Rest Day'", max_length=100)),
                ('description', models.TextField(blank=True, help_text="General instructions for the day's workout.")),
                ('is_rest_day', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='rest.fitnessplan')),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Push-ups', 'Squats', 'Ampe (Jumping Game)'", max_length=100)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.CharField(help_text="e.g., '10-12', 'AMRAP (As Many Reps As Possible)'", max_length=50)),
                ('rest_period_seconds', models.PositiveIntegerField(help_text='Rest time in seconds between sets.')),
                ('notes', models.TextField(blank=True, help_text='Specific instructions or Ghanaian context.')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='rest.workoutday')),
            ],
        ),
    ]
