# Generated by Django 5.2.3 on 2025-06-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessplan',
            name='goal_at_creation',
            field=models.CharField(blank=True, help_text="The user's goal when this plan was created.", max_length=50, null=True),
        ),
    ]
