# Generated by Django 5.2.3 on 2025-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_fitnessplan_goal_at_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='portion_size',
            field=models.CharField(blank=True, help_text="e.g., '1 medium ladle', '2 pieces of chicken'", max_length=100, null=True),
        ),
    ]
