# Generated by Django 5.2.3 on 2025-07-11 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preferences',
            field=models.TextField(blank=True, help_text="e.g., 'no red meat', 'prefers fish', 'allergic to groundnuts'", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionday',
            unique_together={('plan', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='MealTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('portion_consumed', models.FloatField(default=1.0, help_text='Portion consumed (1.0 = full portion, 0.5 = half, etc.)')),
                ('notes', models.TextField(blank=True, help_text='User notes about this meal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='rest.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
                'unique_together': {('meal', 'user', 'date_completed')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('sets_completed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='User notes about this workout session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='rest.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_completed'],
                'unique_together': {('exercise', 'user', 'date_completed')},
            },
        ),
    ]
