# Generated by Django 5.2.3 on 2025-07-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_fitnessplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionday',
            name='target_water_litres',
            field=models.FloatField(blank=True, help_text='Recommended water intake in liters.', null=True),
        ),
    ]
