# Generated by Django 5.2.3 on 2025-07-22 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_nutritionday_target_water_litres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, help_text='Specific instructions or Ghanaian context.', null=True),
        ),
        migrations.AlterField(
            model_name='mealtracking',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes about this meal', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionday',
            name='notes',
            field=models.TextField(blank=True, help_text="General advice for the day, e.g., 'Drink 3L of water.'", null=True),
        ),
        migrations.AlterField(
            model_name='workouttracking',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes about this workout session', null=True),
        ),
        migrations.CreateModel(
            name='WaterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('litres_consumed', models.FloatField(default=0.0, help_text='Litres of water consumed')),
                ('notes', models.TextField(blank=True, help_text='User notes about this water intake', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutrition_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_tracking_records', to='rest.nutritionday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
