# Generated by Django 5.2.3 on 2025-08-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_exercise_notes_alter_mealtracking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list of allergies', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disabilities',
            field=models.TextField(blank=True, help_text='Comma-separated list of physical limitations', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked_foods',
            field=models.TextField(blank=True, help_text='Comma-separated list of foods you dislike', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_foods',
            field=models.TextField(blank=True, help_text='Comma-separated list of favorite foods', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='E.g., diabetes, hypertension', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very Active (hard exercise/sports 6-7 days a week)'), ('athlete', 'Intense daily exercise')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preferences',
            field=models.TextField(blank=True, help_text="e.g., 'none', 'vegetarian', 'vegan', 'halal', ", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance/Performance')], max_length=50, null=True),
        ),
    ]
