# Generated by Django 5.2.3 on 2025-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_profile_allergies_profile_disabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration_mins',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the exercise in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='met_value',
            field=models.FloatField(blank=True, help_text='Metabolic Equivalent of Task value. Represents the intensity of the exercise.', null=True),
        ),
        migrations.AddField(
            model_name='workouttracking',
            name='calories_burned',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
