# Generated by Django 5.2.3 on 2025-08-06 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_exercise_duration_mins_exercise_met_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='added_to_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='breakfast_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='connected_to_google_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dinner_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='lunch_time',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AddField(
            model_name='profile',
            name='snack_time',
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_rest_timer_after_exercise',
            field=models.BooleanField(default=False, help_text='Start a rest timer after completing an exercise.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='track_after_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='workout_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
