# Generated by Django 5.2.3 on 2025-08-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_fitnessplan_added_to_calendar_profile_breakfast_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessplan',
            old_name='added_to_calendar',
            new_name='nutrition_added_to_calendar',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='workout_added_to_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
