# Generated by Django 5.2.3 on 2025-08-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_rename_added_to_calendar_fitnessplan_nutrition_added_to_calendar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='track_after_timer',
            new_name='track_after_rest_timer',
        ),
    ]
