# Generated by Django 5.2.3 on 2025-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_rename_track_after_timer_profile_track_after_rest_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notifications_enabled',
            new_name='notification_reminders_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Enable email reminders for workouts and meals.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='minutes_before_email_reminder',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
