# Generated by Django 5.2.5 on 2025-08-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_rename_notifications_enabled_profile_notification_reminders_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessplan',
            name='is_active',
        ),
    ]
