# Generated by Django 5.2.5 on 2025-08-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_remove_fitnessplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID of the Google Calendar for this plan.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='ID of the Google Calendar event for this meal.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='ID of the Google Calendar event for this workout day.', max_length=255, null=True),
        ),
    ]
